// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load `.env.local` first (Next.js convention), then fall back to `.env`.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
